MultipleFile-Upload/front-to-back/ViewModels/Contact/ContactIndexViewModel.cs
using front_to_back.Models;

namespace front_to_back.ViewModels.Contact
{
    public class ContactIndexViewModel
    {
        public ContractIntroComponent ContractIntroComponent { get; set; }
    }
}

MultipleFile-Upload/front-to-back/Controllers/ContactController.cs
using front_to_back.DAL;
using front_to_back.ViewModels.Contact;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace front_to_back.Controllers
{
    public class ContactController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public ContactController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public async Task<IActionResult> Index()
        {
            var contractIntroComponent = await _appDbContext.ContractIntroComponent.FirstOrDefaultAsync();

            var model = new ContactIndexViewModel
            {
                ContractIntroComponent = contractIntroComponent
            };

            return View(model);
        }
    }
}

MultipleFile-Upload/front-to-back/ViewComponents/ObjectiveComponentViewComponent.cs
using front_to_back.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace front_to_back.ViewComponents
{
    public class ObjectiveComponentViewComponent : ViewComponent
    {
        private readonly AppDbContext _appDbContext;

        public ObjectiveComponentViewComponent(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var objectiveComponents = await _appDbContext.ObjectiveComponents.ToListAsync();
            return View(objectiveComponents);
        }
    }
}

MultipleFile-Upload/front-to-back/Views/Contact/Index.cshtml
@using front_to_back.ViewModels.Contact;
@model ContactIndexViewModel

<!-- Start Banner Hero -->
<section class="bg-light">
    <div class="container py-4">
        <div class="row align-items-center justify-content-between">
            <div class="contact-header col-lg-4">
                <h1 class="h2 pb-3 text-primary">@Model.ContractIntroComponent?.Title</h1>
                @Html.Raw(Model.ContractIntroComponent?.Description)
            </div>
            <div class="contact-img col-lg-5 align-items-end col-md-4">
                <img src="@Model.ContractIntroComponent?.FilePath">
            </div>
        </div>
    </div>
</section>
<!-- End Banner Hero -->
@await Component.InvokeAsync("ObjectiveComponent")
<!-- Start Contact -->
<section class="container py-5">

    <h1 class="col-12 col-xl-8 h2 text-left text-primary pt-3">Create success campaign with us!</h1>
    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Elit, sed do eiusmod tempor </h2>
    <p class="col-12 col-xl-8 text-left text-muted pb-5 light-300">
        Incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices
        gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Laboris
        nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit
        in voluptate.
    </p>

    <div class="row pb-4">
        <div class="col-lg-4">

            <div class="contact row mb-4">
                <div class="contact-icon col-lg-3 col-3">
                    <div class="py-3 mb-2 text-center border rounded text-secondary">
                        <i class='display-6 bx bx-news'></i>
                    </div>
                </div>
                <ul class="contact-info list-unstyled col-lg-9 col-9  light-300">
                    <li class="h5 mb-0">Media Contact</li>
                    <li class="text-muted">Mr. John Doe</li>
                    <li class="text-muted">010-020-0340</li>
                </ul>
            </div>

            <div class="contact row mb-4">
                <div class="contact-icon col-lg-3 col-3">
                    <div class="border py-3 mb-2 text-center border rounded text-secondary">
                        <i class='bx bx-laptop display-6'></i>
                    </div>
                </div>
                <ul class="contact-info list-unstyled col-lg-9 col-9 light-300">
                    <li class="h5 mb-0">Technical Contact</li>
                    <li class="text-muted">Mr. John Stiles</li>
                    <li class="text-muted">010-020-0340</li>
                </ul>
            </div>

            <div class="contact row mb-4">
                <div class="contact-icon col-lg-3 col-3">
                    <div class="border py-3 mb-2 text-center border rounded text-secondary">
                        <i class='bx bx-money display-6'></i>
                    </div>
                </div>
                <ul class="contact-info list-unstyled col-lg-9 col-9 light-300">
                    <li class="h5 mb-0">Billing Contact</li>
                    <li class="text-muted">Mr. Richard Miles</li>
                    <li class="text-muted">010-020-0340</li>
                </ul>
            </div>

        </div>


        <!-- Start Contact Form -->
        <div class="col-lg-8 ">
            <form class="contact-form row" method="post" action="#" role="form">

                <div class="col-lg-6 mb-4">
                    <div class="form-floating">
                        <input type="text" class="form-control form-control-lg light-300" id="floatingname" name="inputname" placeholder="Name">
                        <label for="floatingname light-300">Name</label>
                    </div>
                </div><!-- End Input Name -->

                <div class="col-lg-6 mb-4">
                    <div class="form-floating">
                        <input type="text" class="form-control form-control-lg light-300" id="floatingemail" name="inputemail" placeholder="Email">
                        <label for="floatingemail light-300">Email</label>
                    </div>
                </div><!-- End Input Email -->

                <div class="col-lg-6 mb-4">
                    <div class="form-floating">
                        <input type="text" class="form-control form-control-lg light-300" id="floatingphone" name="inputphone" placeholder="Phone">
                        <label for="floatingphone light-300">Phone</label>
                    </div>
                </div><!-- End Input Phone -->

                <div class="col-lg-6 mb-4">
                    <div class="form-floating">
                        <input type="text" class="form-control form-control-lg light-300" id="floatingcompany" name="inputcompany" placeholder="Company Name">
                        <label for="floatingcompany light-300">Company Name</label>
                    </div>
                </div><!-- End Input Company Name -->

                <div class="col-12">
                    <div class="form-floating mb-4">
                        <input type="text" class="form-control form-control-lg light-300" id="floatingsubject" name="inputsubject" placeholder="Subject">
                        <label for="floatingsubject light-300">Subject</label>
                    </div>
                </div><!-- End Input Subject -->

                <div class="col-12">
                    <div class="form-floating mb-3">
                        <textarea class="form-control light-300" rows="8" placeholder="Message" id="floatingtextarea"></textarea>
                        <label for="floatingtextarea light-300">Message</label>
                    </div>
                </div><!-- End Textarea Message -->

                <div class="col-md-12 col-12 m-auto text-end">
                    <button type="submit" class="btn btn-secondary rounded-pill px-md-5 px-4 py-2 radius-0 text-light light-300">Send Message</button>
                </div>

            </form>
        </div>
        <!-- End Contact Form -->


    </div>
</section>
<!-- End Contact -->